/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AppSuperAdminRouteImport } from './routes/app.super-admin'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppManagersRouteImport } from './routes/app.managers'
import { Route as AppFilesLinksRouteImport } from './routes/app.files-links'
import { Route as AppContentStudioRouteImport } from './routes/app.content-studio'
import { Route as AppBloggersRouteImport } from './routes/app.bloggers'
import { Route as AppBloggerRouteImport } from './routes/app.blogger'
import { Route as AppAuditLogRouteImport } from './routes/app.audit-log'
import { Route as AppAtelierRouteImport } from './routes/app.atelier'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as LangShopInfoRouteImport } from './routes/$lang.shop-info'
import { Route as LangReleasesRouteImport } from './routes/$lang.releases'
import { Route as LangNewsletterRouteImport } from './routes/$lang.newsletter'
import { Route as LangLoginRouteImport } from './routes/$lang.login'
import { Route as LangLinksRouteImport } from './routes/$lang.links'
import { Route as LangApplyRouteImport } from './routes/$lang.apply'
import { Route as LangAboutRouteImport } from './routes/$lang.about'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AppSuperAdminRoute = AppSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppManagersRoute = AppManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesLinksRoute = AppFilesLinksRouteImport.update({
  id: '/files-links',
  path: '/files-links',
  getParentRoute: () => AppRoute,
} as any)
const AppContentStudioRoute = AppContentStudioRouteImport.update({
  id: '/content-studio',
  path: '/content-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppBloggersRoute = AppBloggersRouteImport.update({
  id: '/bloggers',
  path: '/bloggers',
  getParentRoute: () => AppRoute,
} as any)
const AppBloggerRoute = AppBloggerRouteImport.update({
  id: '/blogger',
  path: '/blogger',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAtelierRoute = AppAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const LangShopInfoRoute = LangShopInfoRouteImport.update({
  id: '/shop-info',
  path: '/shop-info',
  getParentRoute: () => LangRoute,
} as any)
const LangReleasesRoute = LangReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => LangRoute,
} as any)
const LangNewsletterRoute = LangNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangLinksRoute = LangLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => LangRoute,
} as any)
const LangApplyRoute = LangApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/links': typeof LangLinksRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/newsletter': typeof LangNewsletterRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/shop-info': typeof LangShopInfoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/atelier': typeof AppAtelierRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/blogger': typeof AppBloggerRoute
  '/app/bloggers': typeof AppBloggersRoute
  '/app/content-studio': typeof AppContentStudioRoute
  '/app/files-links': typeof AppFilesLinksRoute
  '/app/managers': typeof AppManagersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/super-admin': typeof AppSuperAdminRoute
  '/$lang/': typeof LangIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/links': typeof LangLinksRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/newsletter': typeof LangNewsletterRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/shop-info': typeof LangShopInfoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/atelier': typeof AppAtelierRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/blogger': typeof AppBloggerRoute
  '/app/bloggers': typeof AppBloggersRoute
  '/app/content-studio': typeof AppContentStudioRoute
  '/app/files-links': typeof AppFilesLinksRoute
  '/app/managers': typeof AppManagersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/super-admin': typeof AppSuperAdminRoute
  '/$lang': typeof LangIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/apply': typeof LangApplyRoute
  '/$lang/links': typeof LangLinksRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/newsletter': typeof LangNewsletterRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/shop-info': typeof LangShopInfoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/atelier': typeof AppAtelierRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/blogger': typeof AppBloggerRoute
  '/app/bloggers': typeof AppBloggersRoute
  '/app/content-studio': typeof AppContentStudioRoute
  '/app/files-links': typeof AppFilesLinksRoute
  '/app/managers': typeof AppManagersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/super-admin': typeof AppSuperAdminRoute
  '/$lang/': typeof LangIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/app'
    | '/$lang/about'
    | '/$lang/apply'
    | '/$lang/links'
    | '/$lang/login'
    | '/$lang/newsletter'
    | '/$lang/releases'
    | '/$lang/shop-info'
    | '/app/admin'
    | '/app/applications'
    | '/app/atelier'
    | '/app/audit-log'
    | '/app/blogger'
    | '/app/bloggers'
    | '/app/content-studio'
    | '/app/files-links'
    | '/app/managers'
    | '/app/profile'
    | '/app/super-admin'
    | '/$lang/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/apply'
    | '/$lang/links'
    | '/$lang/login'
    | '/$lang/newsletter'
    | '/$lang/releases'
    | '/$lang/shop-info'
    | '/app/admin'
    | '/app/applications'
    | '/app/atelier'
    | '/app/audit-log'
    | '/app/blogger'
    | '/app/bloggers'
    | '/app/content-studio'
    | '/app/files-links'
    | '/app/managers'
    | '/app/profile'
    | '/app/super-admin'
    | '/$lang'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/app'
    | '/$lang/about'
    | '/$lang/apply'
    | '/$lang/links'
    | '/$lang/login'
    | '/$lang/newsletter'
    | '/$lang/releases'
    | '/$lang/shop-info'
    | '/app/admin'
    | '/app/applications'
    | '/app/atelier'
    | '/app/audit-log'
    | '/app/blogger'
    | '/app/bloggers'
    | '/app/content-studio'
    | '/app/files-links'
    | '/app/managers'
    | '/app/profile'
    | '/app/super-admin'
    | '/$lang/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/app/super-admin': {
      id: '/app/super-admin'
      path: '/super-admin'
      fullPath: '/app/super-admin'
      preLoaderRoute: typeof AppSuperAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/managers': {
      id: '/app/managers'
      path: '/managers'
      fullPath: '/app/managers'
      preLoaderRoute: typeof AppManagersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files-links': {
      id: '/app/files-links'
      path: '/files-links'
      fullPath: '/app/files-links'
      preLoaderRoute: typeof AppFilesLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content-studio': {
      id: '/app/content-studio'
      path: '/content-studio'
      fullPath: '/app/content-studio'
      preLoaderRoute: typeof AppContentStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bloggers': {
      id: '/app/bloggers'
      path: '/bloggers'
      fullPath: '/app/bloggers'
      preLoaderRoute: typeof AppBloggersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blogger': {
      id: '/app/blogger'
      path: '/blogger'
      fullPath: '/app/blogger'
      preLoaderRoute: typeof AppBloggerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-log': {
      id: '/app/audit-log'
      path: '/audit-log'
      fullPath: '/app/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atelier': {
      id: '/app/atelier'
      path: '/atelier'
      fullPath: '/app/atelier'
      preLoaderRoute: typeof AppAtelierRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/$lang/shop-info': {
      id: '/$lang/shop-info'
      path: '/shop-info'
      fullPath: '/$lang/shop-info'
      preLoaderRoute: typeof LangShopInfoRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/releases': {
      id: '/$lang/releases'
      path: '/releases'
      fullPath: '/$lang/releases'
      preLoaderRoute: typeof LangReleasesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/newsletter': {
      id: '/$lang/newsletter'
      path: '/newsletter'
      fullPath: '/$lang/newsletter'
      preLoaderRoute: typeof LangNewsletterRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/links': {
      id: '/$lang/links'
      path: '/links'
      fullPath: '/$lang/links'
      preLoaderRoute: typeof LangLinksRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/apply': {
      id: '/$lang/apply'
      path: '/apply'
      fullPath: '/$lang/apply'
      preLoaderRoute: typeof LangApplyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangApplyRoute: typeof LangApplyRoute
  LangLinksRoute: typeof LangLinksRoute
  LangLoginRoute: typeof LangLoginRoute
  LangNewsletterRoute: typeof LangNewsletterRoute
  LangReleasesRoute: typeof LangReleasesRoute
  LangShopInfoRoute: typeof LangShopInfoRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangApplyRoute: LangApplyRoute,
  LangLinksRoute: LangLinksRoute,
  LangLoginRoute: LangLoginRoute,
  LangNewsletterRoute: LangNewsletterRoute,
  LangReleasesRoute: LangReleasesRoute,
  LangShopInfoRoute: LangShopInfoRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAtelierRoute: typeof AppAtelierRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppBloggerRoute: typeof AppBloggerRoute
  AppBloggersRoute: typeof AppBloggersRoute
  AppContentStudioRoute: typeof AppContentStudioRoute
  AppFilesLinksRoute: typeof AppFilesLinksRoute
  AppManagersRoute: typeof AppManagersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSuperAdminRoute: typeof AppSuperAdminRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppAtelierRoute: AppAtelierRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppBloggerRoute: AppBloggerRoute,
  AppBloggersRoute: AppBloggersRoute,
  AppContentStudioRoute: AppContentStudioRoute,
  AppFilesLinksRoute: AppFilesLinksRoute,
  AppManagersRoute: AppManagersRoute,
  AppProfileRoute: AppProfileRoute,
  AppSuperAdminRoute: AppSuperAdminRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
