-- Clear newsletter test history.
-- IMPORTANT:
-- 1. Run sql/2026-06-19-clear-newsletter-tests-preview.sql first.
-- 2. Run this only if the preview looks correct.
--
-- This deletes:
-- - newsletter campaigns
-- - notification_queue rows generated by newsletter campaigns
-- - newsletter-related audit log rows
--
-- This keeps:
-- - newsletter_subscribers
-- - profiles/users
-- - products/content/assets

begin;

delete from public.notification_queue
where metadata @> '{"source":"newsletter"}'::jsonb;

delete from public.audit_logs
where target_type in ('newsletter', 'newsletter_campaign', 'newsletter_subscriber')
   or action ilike 'newsletter_%';

delete from public.newsletter_campaigns;

commit;
